version: "3.9"

services:

  postgres:
    image: postgres:15
    container_name: graphrank_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: graphrank
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: graphrank_redis
    ports:
      - "6379:6379"

  api:
    build: .
    container_name: graphrank_api
    depends_on:
      - postgres
      - redis
    ports:
      - "8000:8000"

  spark:
    image: bitnami/spark:latest
    container_name: graphrank_spark
    ports:
      - "8080:8080"