services:
  postgres:
    image: postgres:15
    container_name: graphrank_postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: graphrank_redis
    ports:
      - "6379:6379"

  api:
    build: .
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    volumes:
      - shared_data:/app/data

  daemon:
    build:
      context: .
      dockerfile: Dockerfile.daemon
    container_name: graphrank_daemon
    command: ["python", "scripts/pipeline_daemon.py"]
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    volumes:
      - shared_data:/app/data

  stream-processor:
    build:
      context: .
      dockerfile: Dockerfile.daemon
    container_name: graphrank_stream
    command: ["python", "spark_jobs/stream_processor.py"]
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    volumes:
      - shared_data:/app/data

  nginx:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend:/usr/share/nginx/html:ro
    depends_on:
      - api

volumes:
  pgdata:
  shared_data: